kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: details-v1
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'details:v1'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:latest'
      buildArgs:
        - name: service_version
          value: 'v1'        
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/booking-info.git'
      ref: main
    contextDir: src/details
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
