kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: mongodb
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'mongodb:latest'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/ibmmas/mongo:4.4.21'
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/booking-info.git'
      ref: main
    contextDir: src/mongodb
  triggers:
    - type: ConfigChange
  runPolicy: Serial
