kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: reviews-v3
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'reviews:v3'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile  
      buildArgs:
        - name: service_version
          value: 'v3'       
        - name: enable_ratings
          value: 'true'      
        - name: star_color
          value: 'red'      
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/booking-info.git'
      ref: main
    contextDir: src/reviews/reviews-application
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
